token = "" # Токен сообщества ВКонтакте

buttons_text = "shuex"
message_text = "🤘🏻" # Текст сообщения. Если короче 4096 байтов - будет повторён максимальное количество раз

logging_level = "DEBUG"
delay = 2
