token = "52b1b760c0c2804f29706b1b738f5519086ccb93b2f3832711f370d30e9656a4ff4a5fff307b32e52c468" # Токен сообщества ВКонтакте

buttons_text = "vto.pe"
message_text = "🤘🏻" # Текст сообщения. Если короче 4096 байтов - будет повторён максимальное количество раз

logging_level = "DEBUG"
delay = 1.0
